### PR TITLE
Solved #151 by keeping track of if first connection was successful

### PR DESCRIPTION
**Pull request by TotalKrill**
Tested it by first connecting to "broker.hivemq.com", with different reconnectoptions, 
Then disconnecting the internet connection, and noticed it tried to reconnect with AfterFirstSuccess(0)

then testing it by connecting to "braker.hivemq.com" (misspelled) with different options, and got an error returned in all cases except when using reconnectoption Always

### CODE REVIEW

**Comment by tekjar** [comment]
Hi. I vaguely remember fixing this in a branch which isn't merged yet. The root cause of this is due to connection.rs not having any unit tests. Can you please use your fork till I fix this?

**Comment by TotalKrill** [comment]
Sure no problems, looking forward to you continuing work on this in June, let me know if there is something I can help with.

**Comment by TotalKrill** [comment]
Could we reconsider merging this, there is minimal amount of changes in this and thus it could easily be reverted if needed.

**Comment by tekjar** [comment]
Sorry for the delay here. It's mid June and I'm going to start my work on this crate starting tomorrow. Thanks for the contribution :)

**Comment by TotalKrill** [comment]
thanks! Looking forward to it! :)

**Pull request merged**
